name: Build RPM

on:
  push:
  workflow_dispatch:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.set-dirs.outputs.changed_dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed rpm subdirectories
        id: set-dirs
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} |
              grep '^rpms/' |
              cut -d/ -f2 |
              sort -u |
              jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed_dirs=$dirs" >> $GITHUB_OUTPUT

  build-rpm:
    needs: find-changes
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nathanjrowe/rpmbuilder:main
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-changes.outputs.changed_dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move files
        run: |
          mv rpms/${{ matrix.dir }}/*.spec /root/rpmbuild/SPECS/
          mv rpms/${{ matrix.dir }}/* /root/rpmbuild/SOURCES/ || true

      - name: Build Dependencies
        run: yum-builddep -y /root/rpmbuild/SPECS/*.spec

      - name: Download sources
        run: |
          pushd /root/rpmbuild/SOURCES/
          [ -f sources ] && cat sources | xargs curl -L0 -O || echo "No sources file"
          popd

      - name: Build SRPM
        run: |
          rpmbuild -bs /root/rpmbuild/SPECS/*.spec \
            --define "_topdir /root/rpmbuild" \
            --define "_srcrpmdir /root/rpmbuild/SRPMS"

      - name: Rebuild SRPM
        run: |
          rpmbuild --rebuild /root/rpmbuild/SRPMS/*.src.rpm
            --define "_topdir /root/rpmbuild"

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          path: /root/rpmbuild/RPMS/*.rpm
