name: Build RPM

on:
  push:
  workflow_dispatch:

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.set-dirs.outputs.changed_dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed rpm subdirectories
        id: set-dirs
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} |
              grep '^rpms/' |
              cut -d/ -f2 |
              sort -u |
              jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed_dirs=$dirs" >> $GITHUB_OUTPUT

  build-rpm:
    needs: find-changes
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nathanjrowe/rpmbuilder:sha256-bc2de42f6240273c2901c65e8abe3605408156b27281aa879903014bb27db935.sig
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-changes.outputs.changed_dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Move files
        run: |
          mkdir -p SPECS SOURCES SRPMS
          mv rpms/${{ matrix.dir }}/*.spec SPECS/
          mv rpms/${{ matrix.dir }}/* SOURCES/ || true

      - name: Build Dependencies
        run: yum-builddep -y SPECS/*.spec

      - name: Download sources
        run: |
          pushd SOURCES/
          [ -f sources ] && cat sources | xargs curl -L0 -O || echo "No sources file"
          popd

      - name: Build SRPM
        run: rpmbuild -bs SPECS/*.spec --define "_srcrpmdir $GITHUB_WORKSPACE/SRPMS"

      - name: Upload SRPM artifact
        uses: actions/upload-artifact@v4
        with:
          path: SRPMS/*.src.rpm
