# This is a basic workflow to help you get started with Actions
name: Build RPM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    find-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.set-dirs.outputs.changed_dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get list of changed rpm subdirectories
        id: set-dirs
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} |
              grep '^rpms/' |
              cut -d/ -f2 |
              sort -u |
              jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed_dirs=$dirs" >> $GITHUB_OUTPUT
  build-rpm:
    needs: find-changes
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nathanjrowe/rpmbuilder:latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.find-changes.outputs.changed_dirs) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Move files
        run: |
          mv $GITHUB_WORKSPACE/${{ matrix.dir }}/*.spec SPECS/
          mv $GITHUB_WORKSPACE/${{ matrix.dir }}/* SOURCES/
          
      - name: Build Dependencies
        run: yum-buildep SPECS/*.spec

      - name: Download sources
        run: |
          pushd SOURCES/
          cat sources | xargs curl -L0 -O
          popd

      - name: Build SRPM
        run: rpmbuild -bs SPECS/*.spec

      - name: Upload SRPM artifact
        uses: actions/upload-artifact@v4
        with:
          path: SRPMS/*.srpm
