# This is a basic workflow to help you get started with Actions

name: Build RPM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-srpm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nathanjrowe/rpmbuilder:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Move files
        run: |
          mv $GITHUB_WORKSPACE/*.spec SPECS/
          mv $GITHUB_WORKSPACE/* SOURCES/
          
      - name: Build Dependencies
        run: yum-buildep SPECS/*.spec

      - name: Download sources
        run: |
          pushd SOURCES/
          cat sources | xargs curl -L0 -O
          popd

      - name: Build SRPM
        run: rpmbuild -bs SPECS/*.spec

      - name: Upload SRPM artifact
        uses: actions/upload-artifact@v4
        with:
          path: SRPMS/*.srpm

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
